sudo: required

language: cpp

services:
  - docker

before_install:
- docker build --no-cache -t kainlite/whatismyip .
- docker run -d -p 127.0.0.1:11000:11000 kainlite/whatismyip /bin/sh -c "cd /root/whatismyip/; ./bin/whatismyip;"
- docker ps -a

script:
- docker run kainlite/whatismyip /bin/sh -c "cd /root/whatismyip/ && cd build && cmake .. && make && ./test/whatismyip_test"
