language: cpp

sudo: false

addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
    - precise-backports
    packages:
    - cmake
    - time
    - libdouble-conversion-dev
    - libgflags-dev
    - libgoogle-glog-dev
    - g++
    - flex
    - bison
    - libkrb5-dev
    - libsasl2-dev
    - libnuma-dev
    - pkg-config
    - libssl-dev
    - libcap-dev
    - gperf
    - autoconf-archive
    - libevent-dev
    - libtool
    - libboost-all-dev
    - libjemalloc-dev
    - libsnappy-dev
    - wget
    - unzip


install:
  - export CXX=${COMPILER}
  - cd ${TRAVIS_BUILD_DIR}
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - git clone https://github.com/facebook/proxygen proxygen
  - cd proxygen/proxygen
  - ./deps.sh
  - cd ..
  - mkdir -p build
  - cd build
  - cmake ..
  - make 
  - ctest -v
